"""simplify_thread_turn_steps

Revision ID: d54da0e106ee
Revises: 219e20ee3b9c
Create Date: 2026-01-28 21:33:38.799096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd54da0e106ee'
down_revision: Union[str, None] = '219e20ee3b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turn_results_turn_id'), table_name='turn_results')
    op.drop_table('turn_results')
    op.add_column('thread_turns', sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('thread_turns', 'analysis')
    op.drop_column('thread_turns', 'error_message')
    op.drop_column('thread_turns', 'operations_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread_turns', sa.Column('operations_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('thread_turns', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('thread_turns', sa.Column('analysis', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('thread_turns', 'steps')
    op.create_table('turn_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('turn_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_columns', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('formulas', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('output_file', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('output_file_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['turn_id'], ['thread_turns.id'], name=op.f('turn_results_turn_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('turn_results_pkey'))
    )
    op.create_index(op.f('ix_turn_results_turn_id'), 'turn_results', ['turn_id'], unique=True)
    # ### end Alembic commands ###
